### ISSUE TITLE
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetDialogsRequest)

### ISSUE THREAD

**Issue by ljhOfGithub** [edogab33/telegram-groups-crawler#2]
The first time I touched Telethon, I changed the api_id and api_hash, and then ran the program, but the following error was reported:
Traceback (most recent call last):
  File "scraper.py", line 370, in <module>
    client.loop.run_until_complete(main())
  File "/root/.miniconda3/envs/python38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "scraper.py", line 41, in main
    await init_empty()
  File "scraper.py", line 187, in init_empty
    async for dialog in client.iter_dialogs():
  File "/root/.miniconda3/envs/python38/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/root/.miniconda3/envs/python38/lib/python3.8/site-packages/telethon/client/dialogs.py", line 53, in _load_next_chunk
    r = await self.client(self.request)
  File "/root/.miniconda3/envs/python38/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/root/.miniconda3/envs/python38/lib/python3.8/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetDialogsRequest)
- May I ask what modifications I need to make to run this program? Do I need a Telegram group file? Can you provide a simple example? Thank you.

**Comment by edogab33** [comment]
Hi, 

The problem is that you are using a bot session instead of a user one.
Indeed, the crawler works only for normal accounts because Telegram does not allow bots to join groups or channels autonomously, so what the script does is to use a user in order to crawl and scrape data. Of course it is not real user because we are automating it and we are not using it as intended.

However in this case the error is stating that you cannot iterate through your message dialogs.

To solve the problem you can get an API key and an hash [here](https://my.telegram.org/auth) by inserting your telephone number. If you don't want to give your real one, there are several services out there where you can get a number by paying in crypto, but I guess you will need these services anyway if you want to collect a large amount of data.

Let me know if this helped.

**Comment by ljhOfGithub** [comment]
> Hi,
> 
> The problem is that you are using a bot session instead of a user one. Indeed, the crawler works only for normal accounts because Telegram does not allow bots to join groups or channels autonomously, so what the script does is to use a user in order to crawl and scrape data. Of course it is not real user because we are automating it and we are not using it as intended.
> 
> However in this case the error is stating that you cannot iterate through your message dialogs.
> 
> To solve the problem you can get an API key and an hash [here](https://my.telegram.org/auth) by inserting your telephone number. If you don't want to give your real one, there are several services out there where you can get a number by paying in crypto, but I guess you will need these services anyway if you want to collect a large amount of data.
> 
> Let me know if this helped.

Yes,it helps!Thank you.I use the phone number instead of bot token to build client and it works.

**Comment by edogab33** [comment]
You are welcome! Feel free to open another issue if needed
